export default {
    PROCS: 4,
    STAT_TYPES: [
        'atk',
        'atk%',
        'def',
        'def%',
        'hp',
        'hp%',
        'accuracy',
        'res',
        'cr',
        'spd',
        'cd',
    ],
    STAT_LABELS: {
        atk: 'ATK',
        'atk%': 'ATK%',
        def: 'DEF',
        'def%': 'DEF%',
        hp: 'HP',
        'hp%': 'HP%',
        accuracy: 'Accuracy',
        res: 'Resistance',
        cr: 'CRI Rate',
        spd: 'SPD',
        cd: 'CRI Damage',
    },
    RUNE_TYPES: [
        'accuracy',
        'blade',
        'despair',
        'destroy',
        'determination',
        'endure',
        'energy',
        'enhance',
        'fatal',
        'fight',
        'focus',
        'guard',
        'nemesis',
        'rage',
        'revenge',
        'seal',
        'shield',
        'swift',
        'tolerance',
        'vampire',
        'violent',
        'will',
    ],
    RUNE_NUMBERS: [1, 2, 3, 4, 5, 6],
    RUNE_PROPERTIES: {
        1: ['atk'],
        2: ['spd', 'def%', 'atk%', 'hp%', 'hp', 'atk', 'def'],
        3: ['def'],
        4: ['cr', 'cd', 'def%', 'atk%', 'hp%', 'hp', 'atk', 'def'],
        5: ['hp'],
        6: ['res', 'accuracy', 'def%', 'atk%', 'hp%', 'hp', 'atk', 'def'],
    },
    RANGES: {
        'atk%': { min: 5, max: 8 },
        'hp%': { min: 5, max: 8 },
        'def%': { min: 5, max: 8 },
        spd: { min: 4, max: 6 },
        cr: { min: 4, max: 6 },
        cd: { min: 4, max: 7 },
        accuracy: { min: 4, max: 8 },
        res: { min: 4, max: 8 },
        hp: { min: 135, max: 375 },
        def: { min: 10, max: 20 },
        atk: { min: 10, max: 20 },
    },
};
